### ISSUE TITLE
Runtime Error in fritzbox_file_session.py (Python 3.9.x)

### ISSUE THREAD

**Issue by wvogel** [ma4nn/fritzbox-munin-fast#16]
**Solved runtime error**
I am experiencing runtime errors for serveral plugins because of line 40 in _fritzbox_file_session.py_:
`  def load(self) -> None | str:`
Might be related to a Python version below 3.10 (3.9.2 is current on Raspberry Pi OS) and can be solved by adding "":
`  def load(self) -> "None | str":`
All plugins run smoothly after this change.
[I included this in my pull request]

**Comment by ma4nn** [comment]
Hi @wvogel,

thanks for your feedback! 

Yes you're right, this is because of the (old) Python version from 2021-02. As mentioned in the [README](https://github.com/ma4nn/fritzbox-munin-fast/blob/master/README.md) the minimum required version currently is 3.10. But if 3.9.2 is the default on PiOS and it is supported until 2025-10, perhaps it makes sense to downgrade the requirement to >= 3.9.2 then.

**Comment by wvogel** [comment]
Thanks @ma4nn,
it seems like this is actually the only line of code that would require 3.10. Running on 3.9.2 perfectly now with the changes suggested.
Installing a newer Python version on a P4 with SSD takes about 1 hour, so downgrading requirements would be quite an option.
